version: '3.7'
services:
  rabbit: 
    environment:
      RABBITMQ_DEFAULT_USER: merUser
      RABBITMQ_DEFAULT_PASS: passwordMER
      RABBITMQ_DEFAULT_VHOST: "/"
    image: "rabbitmq:3-management"
    deploy: 
      restart_policy:
        condition: on-failure
    networks:
      dockernet:
        ipv4_address: 172.32.0.10
    ports:
        - "15672:15672"
        - "5672:5672"
  vidextrator:
    image: imagevideoextrator
    build:
      context: .
      dockerfile: vidextraction.Dockerfile
    volumes:
        - type: bind
          source: /vagrant/Audios
          target: /vidExtrator/Audios
    restart: on-failure
    depends_on:
      - rabbit
    networks:
        - dockernet
  featextraction:
    image: mtgupf/essentia
    build:
      context: .
      dockerfile: featuresextraction.Dockerfile
    volumes:
        - type: bind
          source: /vagrant/Audios
          target: /Audios
    restart: on-failure
    depends_on:
      - rabbit
    networks:
        - dockernet
  musicclass:
    image: python
    build:
      context: .
      dockerfile: classifymusic.Dockerfile
    restart: on-failure 
    networks:
        - dockernet
    volumes:
      - type: bind
        source: /vagrant/MusicClassification/classification.txt
        target: /classification.txt

        
volumes:
  audios:
  classifications:

networks:
    dockernet:
        external: true